# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  chapman_identities_password: <%= ENV["CHAPMAN_IDENTITIES_PASSWORD"] %>
  chapman_identities_username: <%= ENV["CHAPMAN_IDENTITIES_USERNAME"] %>
  chapman_identities_base_url: <%= ENV["CHAPMAN_IDENTITIES_BASE_URL"] %>

development:
  <<: *common
  secret_key_base: 

test:
  <<: *common
  secret_key_base: 

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bugsnag_api_key: <%= ENV["BUGSNAG_API_KEY"] %>

production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bugsnag_api_key: <%= ENV["BUGSNAG_API_KEY"] %>
